<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup Condition="'$(CONFIGURATION)' == 'Debug' Or '$(BuildDocFx)' == 'true'">
    <ProjectReference Include="..\..\src\Devices\Devices.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(CONFIGURATION)' == 'Release' And '$(BuildDocFx)' != 'true'">
    <PackageReference Include="AdaptArch.Devices" />
  </ItemGroup>

</Project>
