<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Devices\Devices.csproj" />
    <ProjectReference Include="..\..\src\Devices.DependencyInjection\Devices.DependencyInjection.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="PrintFiles\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
